### PR TITLE
Integrate create an intervention or red-flag record UI with back end

### PR DESCRIPTION
**Pull request by kalsmic**
This pull request integrates the front end UI with the API back end for both creating a red-flag and an intervention record.
One thing I have not been able to do is to add a search input box for the map so that the user can find the desired location with ease. Any kind of assistance to this regard is highly welcome.
Please kindly review the functionality for creating an incident record and give feedback.
@Nicholus @Rhytah @JamesMudidi @Sanya-kenneth @frankopkusianwar @AtamaZack @ManuelDominic @KabohaJeanMark @nadralia @reifred @llwasampijja @richien @Genza999 @3Nakajugo @e-ian @Manorlds-Eaglespark @PatrickMugayaJoel @bisonlou @v1b3m @mwinel
LInk to UI https://kalsmic.github.io/iReporterApi/UI/index.html

### CODE REVIEW

**Review by bisonlou — APPROVED** [review]
This is good work.
I tried to create an account and 'Pa$$word123' is regarded as a weak password.
So i basically couldn't create an account.

**Comment by NicholusMuwonge** [comment]
I cant seem to find yo ui link, try and include it the next pr

**Comment by kalsmic** [comment]
> I cant seem to find yo ui link, try and include it the next pr
@NicholusMuwonge, sorry about that.
https://kalsmic.github.io/iReporterApi/UI/index.html

**Comment by kalsmic** [comment]
> This is good work.
> I tried to create an account and 'Pa$$word123' is regarded as a weak password.
> So i basically couldn't create an account.

Thanks @bisonlou, I am going to revise the password validation.

**Comment by NicholusMuwonge** [comment]
Ive tried it out, wow nice UI, it seems to be working fine. good job

**Comment by v1b3m** [comment]
Awesome.
Keep on

**Pull request merged**
