### PR TITLE
Api

### PR DESCRIPTION
**Pull request by kalsmic**
Please Kindly review and give feedback
@Kengowada @3Nakajugo @Anguandia @araali1 @bakersen @bashirdeveloper @bekeplar @bisonlou @CandySusan @davicken @dtnnml @E-ian @erioc @ernesthenry @fionaharriet @Genza999  @HabibSentongo @HarrietAkot @HarunaIbnYusuf @JammyKalungi @jennizalwango @jkMugabe @joekirumira @k7ko @kabaliisa @KapsonLabs @kayongopique @kdenno @Kwandera @kyakusahmed @Kyeza @lizz24 @llwasampijja @LynetteMK @Manorlds-Eaglespark @masete @Mastula77 @MukuruH @mwes23 @nadralia @nanfuka @NANKYAPHIONA @Natalie-abbie @noahkalyesubula @PatrickMugayaJoel @reifred @richien @ringtho @StephenCMwanika @v1b3m
I would also like to try out documenting the API with Swagger but I have not figured out how to yet, I am trying to find resources for it.

### CODE REVIEW

**Comment by PatrickMugayaJoel** [comment]
i have been trying the heroku links you listed on the '404 handler page'. I have had no success accessing any.

**Comment by kalsmic** [comment]
@PatrickMugayaJoel let me cross check that issue

**Comment by kalsmic** [comment]
@PatrickMugayaJoel I have revised the links on the '404 handler page' though i noticed i also have to add one for the 405 error

**Comment by kalsmic** [comment]
I am going to work on the README  to better guide how users can try out the API because this is one of the issues i have received from the feedback here and in the slack channel where I shared the link.

**Pull request closed without merging**
