### PR TITLE
API documentation for iReporter v1

### PR DESCRIPTION
**Pull request by kalsmic**
Hi Guys? Please kindly check out my API documentation and advise where need be.
All feedback is welcome!
@llwasampijja,@davicken, @masete, @kapsonlabs, @CandySusan, @Kyeza,  @PatrickMugayaJoel,@MukuruH, @reifred, @jennizalwango

### CODE REVIEW

**Comment by llwasampijja** [comment]
@kalsmic Nice work.
Below are some of the things I noticed while trying out your documentation.

-I think your API will function better if Internal server error is also handled
-On the fetch all red-flags records, I think there is an unintended ' on the 401 response code.
-I have failed to post the example model. I get the 400 error. I noticed it is the same issue even when I try to post it via postman. Perhaps it is something to do with validation.

**Comment by kalsmic** [comment]
Thanks @llwasampijja. Let me check out this issue

**Comment by kalsmic** [comment]
@llwasampijja 
- I made an error in the definition for images and videos, that's why you were getting the 400 error on posting the example data but i have made the correction. images and videos begin with an uppercase letter.
- The 401 error on the route for fetching all red-flags is intentioinal because only authenticated users can access this route. You will either have to log in as admin and get a token or get one by signing up.
- As for the 500 internal error, I am going to add it to the errors handled by the application.
Thanks a million for this review.

**Comment by kalsmic** [comment]
@llwasampijja  how you test for a 500 error. I do not know how to cause the scenario for the internal server error.

**Comment by llwasampijja** [comment]
> @llwasampijja how you test for a 500 error. I do not know how to cause the scenario for the internal server error.
@kalsmic  You are most welcome. 
For testing internal error, You can try to post data in a different format from the accepted one, i.e JSON to a route which doesn't accept JSON format!
As for the unintentional apostrophe (') on the 401, let me send you a pic on slack so you can know what am referring to.
Bless, Selah!

**Comment by kalsmic** [comment]
Thanks @llwasampijja

**Comment by kalsmic** [comment]
Thanks, I have seen the error on the 401, I had an unclosed tag.

**Pull request merged**
